In [4]:
import torch as t 
x = t.randn(3, requires_grad = True)
print(x)
y= x + 2
print(y)

z = y * y * 2
#z = z.mean()
v = t.tensor([0.1, 1.0, 0.001], dtype=t.float32)
z.backward(v)

print(x.grad)

tensor([ 0.2077, -0.3041,  0.7571], requires_grad=True)
tensor([2.2077, 1.6959, 2.7571], grad_fn=<AddBackward0>)
tensor([0.8831, 6.7837, 0.0110])


In [5]:
import torch as t 
x = t.randn(3, requires_grad = True)
print(x)
# x.required_grad_(False)
# x.detach()
with t.no_grad():
# create new tensor without gradient 
    y = x.detach()
    print(y)
    y = x + 2

tensor([0.0117, 0.5646, 1.4845], requires_grad=True)
tensor([0.0117, 0.5646, 1.4845])


In [11]:
weights = t.ones(4, requires_grad=True)

for epoc in range(4):
    model_output = (weights * 3).sum()
    print(model_output) 
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])


In [17]:
import torch as t
weights = t.ones(4, requires_grad=True)

optimizer = t.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()
# weights.grad.zero_()

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor